import type { SecurityProfile, SecurityProfileId } from "@/lib/security/types";

const DEFAULT_CONFIRMATION_PATTERNS: ReadonlyArray<RegExp> = [
  /\b(send|draft and send|trigger|dispatch)\b.{0,40}\b(email|emails)\b/i,
  /\b(send|dispatch|blast|queue)\b.{0,40}\b(bulk|mass|campaign)\b.{0,20}\b(email|emails)\b/i,
  /\b(update|write|sync|push|modify|change|delete)\b.{0,40}\b(crm|record|records|database|admin|system)\b/i,
  /\b(modify|change|rotate|replace|update)\b.{0,40}\b(database_url)\b/i,
  /\b(trigger|fire|invoke|call)\b.{0,40}\b(webhook|webhooks)\b/i,
];

export const SECURITY_PROFILES: Record<SecurityProfileId, SecurityProfile> = {
  customer_support: {
    id: "customer_support",
    description: "Public-facing business assistant for product and support tasks.",
    allowedScopeKeywords: [
      "product",
      "service",
      "feature",
      "pricing",
      "plan",
      "quote",
      "demo",
      "trial",
      "faq",
      "real estate",
      "property",
      "proptech",
      "agent",
      "agents",
      "broker",
      "listing",
      "viewing",
      "support",
      "contact",
      "company",
      "chatbot",
      "automation",
      "website",
      "dashboard",
      "integration",
      "security",
      "compliance",
      "deployment",
      "order",
      "shipping",
      "delivery",
      "return",
      "refund",
      "invoice",
      "payment",
      "booking",
      "appointment",
      "triage",
      "lead",
      "sales",
      "whatsapp",
      "customer",
      "onboarding",
    ],
    allowedScopePatterns: [
      /\b(hi|hello|hey|good morning|good afternoon|good evening|help)\b/i,
      /\b(real estate|property|proptech|listing|viewing|brokerage)\b/i,
    ],
    confirmationPatterns: DEFAULT_CONFIRMATION_PATTERNS,
  },
  lead_analysis: {
    id: "lead_analysis",
    description: "Internal sales intelligence assistant for evaluating lead quality.",
    allowedScopeKeywords: [
      "lead",
      "sales",
      "close probability",
      "qualification",
      "opening line",
      "whatsapp",
      "source",
      "notes",
      "organization",
      "chatbot",
      "follow-up",
    ],
    confirmationPatterns: DEFAULT_CONFIRMATION_PATTERNS,
  },
  demo_generation: {
    id: "demo_generation",
    description: "Internal assistant for building strategic demo payloads.",
    allowedScopeKeywords: [
      "strategic reveal",
      "organization",
      "industry",
      "location",
      "website",
      "whatsapp",
      "intent",
      "competitor",
      "assessment",
      "spark",
      "steps",
      "proposed solution",
    ],
    confirmationPatterns: DEFAULT_CONFIRMATION_PATTERNS,
  },
  follow_up_writer: {
    id: "follow_up_writer",
    description: "Internal assistant for generating B2B follow-up drafts.",
    allowedScopeKeywords: [
      "whatsapp hooks",
      "recipient",
      "organization",
      "industry",
      "location",
      "strategy reveal",
      "landing url",
      "strategic assessment",
      "spark directive",
      "competitor analysis",
      "follow-up",
      "ghost-writer",
    ],
    confirmationPatterns: DEFAULT_CONFIRMATION_PATTERNS,
  },
};

export function getSecurityProfile(
  profileId: SecurityProfileId = "customer_support",
): SecurityProfile {
  return SECURITY_PROFILES[profileId];
}
