ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - prisma
  - protobufjs
  - workerd
